---
nautobot:
  db:
    password: "supersecret"
    # existingSecret: "my-secret"
    # existingSecretPasswordKey: "postgres-password"
  redis:
    password: "supersecret"
postgresql:
  enabled: false
  auth:
    existingSecret: "my-secret"
redis:
  enabled: false
  auth:
    existingSecret: "my-secret"
    existingSecretPasswordKey: "NAUTOBOT_REDIS_PASSWORD"
