---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-env
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
{{- include "nautobot.configMap.env" . | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
{{- include "nautobot.configMap.config" . | nindent 2 }}

{{- if $.Values.nautobot.singleInit -}}
{{- $initJob := (include "nautobot.initJob" .) | mustFromJson -}}
# Duplicate the configmaps for the init job only, they will be deleted by helm after the job succeeds.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-env-init
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations: {{- if .Values.commonAnnotations }}{{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}{{- end }}
    helm.sh/hook: "{{ $initJob.installHook }},{{ $initJob.upgradeHook }}"
    helm.sh/hook-weight: "-6"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
data:
{{- include "nautobot.configMap.env" . | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config-init
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations: {{- if .Values.commonAnnotations }}{{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}{{- end }}
    helm.sh/hook: "{{ $initJob.installHook }},{{ $initJob.upgradeHook }}"
    helm.sh/hook-weight: "-6"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
data:
{{- include "nautobot.configMap.config" . | nindent 2 }}
{{- end }}
