{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    app.kubernetes.io/component: nautobot
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- with .Values.metrics.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ include "common.names.fullname" . }}
      rules:
        - alert: NautobotAbsent
          annotations:
            description: Nautobot has disappeared from Prometheus service discovery.
            summary: Nautobot is down.
          expr: |
            absent(up{job=~".*{{ include "common.names.fullname" . }}.*"} == 1)
          for: 5m
          labels:
            severity: critical
        {{- with .Values.metrics.prometheusRule.rules }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
